apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app : {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}
    spec:
      containers:
        - name : {{ .Release.Name }}-web
          image: {{ .Values.container.image }}
          ports:
            - containerPort: 80
----
apiVersion: bitnami.com/v1alpha1
data:
  foo: ZGtoYWNoLXBhc3M=
kind: Secret
metadata:
  creationTimestamp: "2022-04-07T04:04:41Z"
  name: mysecret
  namespace: default
  resourceVersion: "60421"
  uid: 6243cd3c-b798-44d6-8dc3-e82002624ca1
type: Opaque    
