apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app : {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}
    spec:
      containers:
        - name : {{ .Release.Name }}-web
          image: {{ .Values.container.image }}
          ports:
            - containerPort: 80
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
           {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.container.image }}
          envFrom:
           - configMapRef:
              name: {{ .Release.Name }}-key
           - secretRef:
              name: {{ .Release.Name }}-key
