apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: kube-system
data:
   password: S2hkYXYxLTc= # <- base64 encoded Khdav1-7
   username: ZGtoYWNo # <- base64 encoded dkhach
